services:
  - type: web
    name: classplus-extractor-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: API_ID
        value: 27400172
      - key: API_HASH
        value: 56d0a75c5f9a9de6beb5452aa63c2d36
      - key: BOT_TOKEN
        value: 8204209080:AAHQx2wvrV1yrLoJgrxswYgLBf_mkzXqKHQ
      - key: OWNER_ID
        value: 7540570087
      - key: CHANNEL_ID
        value: -1003414109205
